//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Common.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Common.Constants.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssessmentCriteriaID không được để trống..
        /// </summary>
        internal static string AssessmentCriteriaIDIsEmpty {
            get {
                return ResourceManager.GetString("AssessmentCriteriaIDIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category không hợp lệ.
        /// </summary>
        internal static string CategoryInvalid {
            get {
                return ResourceManager.GetString("CategoryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên lớp không được để trống.
        /// </summary>
        internal static string ClassNameIsEmpty {
            get {
                return ResourceManager.GetString("ClassNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration phải lớn hơn 0.
        /// </summary>
        internal static string DurationInvalid {
            get {
                return ResourceManager.GetString("DurationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration phải là số nguyên hợp lệ.
        /// </summary>
        internal static string DurationWrongType {
            get {
                return ResourceManager.GetString("DurationWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        internal static string EmailInvalidFormat {
            get {
                return ResourceManager.GetString("EmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được để trống.
        /// </summary>
        internal static string EmailIsEmpty {
            get {
                return ResourceManager.GetString("EmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn hình ảnh không được để trống.
        /// </summary>
        internal static string ImageURLIsEmpty {
            get {
                return ResourceManager.GetString("ImageURLIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LecturerID không được để trống.
        /// </summary>
        internal static string LecturerIDIsEmpty {
            get {
                return ResourceManager.GetString("LecturerIDIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số sinh viên tối đa phải lớn hơn hoặc bằng số sinh viên tối thiểu.
        /// </summary>
        internal static string MaxLessThanMin {
            get {
                return ResourceManager.GetString("MaxLessThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số sinh viên tối đa phải lớn hơn 0.
        /// </summary>
        internal static string MaxStudentAcpInvalid {
            get {
                return ResourceManager.GetString("MaxStudentAcpInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinPassingScore phải lớn hơn hoặc bằng 0.
        /// </summary>
        internal static string MinPassingScoreInvalid {
            get {
                return ResourceManager.GetString("MinPassingScoreInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinPassingScore phải là số hợp lệ.
        /// </summary>
        internal static string MinPassingScoreWrongType {
            get {
                return ResourceManager.GetString("MinPassingScoreWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số sinh viên tối thiểu phải lớn hơn 0.
        /// </summary>
        internal static string MinStudentAcpInvalid {
            get {
                return ResourceManager.GetString("MinStudentAcpInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được để trống.
        /// </summary>
        internal static string PasswordIsEmpty {
            get {
                return ResourceManager.GetString("PasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học phí phải lớn hơn hoặc bằng 0.
        /// </summary>
        internal static string PriceOfClassInvalid {
            get {
                return ResourceManager.GetString("PriceOfClassInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredCount phải lớn hơn hoặc bằng 0.
        /// </summary>
        internal static string RequiredCountInvalid {
            get {
                return ResourceManager.GetString("RequiredCountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredCount phải là số nguyên hợp lệ.
        /// </summary>
        internal static string RequiredCountWrongType {
            get {
                return ResourceManager.GetString("RequiredCountWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectID không được để trống.
        /// </summary>
        internal static string SubjectIDIsEmpty {
            get {
                return ResourceManager.GetString("SubjectIDIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyllabusID không được để trống.
        /// </summary>
        internal static string SyllabusIDIsEmpty {
            get {
                return ResourceManager.GetString("SyllabusIDIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bắt đầu dạy phải lớn hơn hiện tại.
        /// </summary>
        internal static string TeachingStartTimeInvalid {
            get {
                return ResourceManager.GetString("TeachingStartTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestType không hợp lệ.
        /// </summary>
        internal static string TestTypeInvalid {
            get {
                return ResourceManager.GetString("TestTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeightPercent phải lớn hơn 0.
        /// </summary>
        internal static string WeightPercentInvalid {
            get {
                return ResourceManager.GetString("WeightPercentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeightPercent phải là số hợp lệ.
        /// </summary>
        internal static string WeightPercentWrongType {
            get {
                return ResourceManager.GetString("WeightPercentWrongType", resourceCulture);
            }
        }
    }
}
